apiVersion: v1
kind: Service
metadata:
  labels:
    run: emr-base-spark
  name: emr-base-spark
  namespace: default
spec:
  ports:
  - port: 88
    targetPort: 80
  selector:
    app: emr-base-spark
